version: '3.8'
services:
  user-auth:
    image: rusithfernando/user-auth:latest
    build: ./user-auth
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - JWT_SECRET=your_strong_secret_here_12345
      - MONGO_URI=mongodb+srv://rusithp:jEDwp09p0wS3HcNa@cluster0.tz2dapj.mongodb.net/userAuthDB?retryWrites=true&w=majority
    depends_on:
      - notification
    networks:
      - app-network

  # user-profile:
  #   image: rusithfernando/user-profile:latest
  #   build: ./user-profile
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./user-profile/.env
  #   networks:
  #     - app-network
  user-profile:
    image: rusithfernando/user-profile:latest
    build: ./user-profile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=your_strong_secret_here_12345
      - MONGO_URI=mongodb+srv://rusithp:jEDwp09p0wS3HcNa@cluster0.tz2dapj.mongodb.net/userAuthDB?retryWrites=true&w=majority
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  notification:
    image: rusithfernando/notification:latest
    build: ./notification
    ports:
      - "3003:3003"
    env_file:
      - ./notification/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



# version: '3.8'
# services:
#   user-auth:
#     image: rusithfernando/user-auth:latest
#     build: ./user-auth
#     ports:
#       - "3002:3002"
#     env_file:
#       - ./user-auth/.env
#     depends_on:
#       - notification
#     networks:
#       - app-network

#   user-profile:
#     image: rusithfernando/user-profile:latest
#     build: ./user-profile
#     ports:
#       - "3001:3001"
#     env_file:
#       - ./user-profile/.env
#     networks:
#       - app-network

#   notification:
#     image: rusithfernando/notification:latest
#     build: ./notification
#     ports:
#       - "3003:3003"
#     env_file:
#       - ./notification/.env
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge